apiVersion: apps/v1
kind: Deployment
metadata:
  name: time_app
spec:
  selector:
    matchLabels:
      app: time_app
  replicas: 1
  template:
    metadata:
      labels:
        app: time_app
    spec:
      containers:
      - name: time_app
        image: time_app:latest
        imagePullPolicy: Never # Crucial for local images
        ports:
        - containerPort: 80
